#!/bin/sh

if [ "$#" = 0 -o "$1" = "-h" -o "$1" = "--help" ];
then
    cat <<END
make_doc_package

Usage:
    make_doc_package <basename>

Description:
    Creates a tar.gz file and a zip file that contain the already generated
    HTML documentation. The name of the archive files will be <basename>.tar.gz
    and <basename>.zip.

Note:
    You can run the script from any directory, it will work. (Unless you copy
    the script itself to somewhere else, in which case it will not.)
END
exit
fi

basename="$1"
dir=`dirname "$0"`
tempdir=`mktemp -d`
old_path=`pwd`

mkdir "$tempdir/$basename"
cp -r "$dir/../doc/_build/html" "$tempdir/$basename"
cp -r "$dir/../doc/_build/doctrees" "$tempdir/$basename"
cd "$tempdir"
echo tar czf "$basename.tar.gz" "$basename"
tar czf "$basename.tar.gz" "$basename"
echo zip -r "$basename.zip" "$basename"
zip -qr "$basename.zip" "$basename"
mv "$basename.tar.gz" "$old_path/"
mv "$basename.zip" "$old_path/"
rm -rf "$tempdir"
